--injections
INSERT INTO item_db ( item_name, strength, category_id)
VALUES
('Adenosine amp', '3mg/ml (2ml)', 4),
('Amikacin amp', '250mg/ml (2ml)', 4),
('Amino Acid + Sorbitol', '500ml', 4),
('Aminophylline amp', '25mg/ml 10ml', 4),
('Amiodarone amp', '50mg/ml 3ml', 4),
('Ampicillin + Sulbactam vial', '1.5g', 4),
('Ampicillin + Sulbactam vial', '750mg', 4),
('Ampicillin vial', '250mg', 4),
('Ampicillin vial', '500mg', 4),
('Ampicillin vial', '1gram', 4),
('Amikacin amp', '125mg/ml', 4),
('Ascorbic acid amp', '250mg/ml (2ml)', 4),
('Azithromycin vial', '500mg', 4),
('Benzylpenicillin vial', '1 Million Unit', 4),
('Calcium Gluconate', '10ml', 4),
('Cefazolin vial', '1g', 4),
('Cefipemi vial', '1g', 4),
('Ceftriaxone vial', '1g', 4),
('Cefotaxime vial', '1g', 4),
('Ceftazidime vial', '1g', 4),
('Cefuroxime vial', '750mg', 4),
('Ciprofloxacin vial', '200mg', 4),
('Clindamycin amp', '150mg/ml (2ml)', 4),
('Clonidine Hydrochloride amp', '150mg/ml (50%)', 4),
('D5050 vial', '500mg/ml (50%)', 4),
('Dexamethasone Phosphate amp', '4mg/ml (2ml', 4),
('Digoxin ampule', '250mcg/ml (2ml)', 4),
('Diphenhydramine Hydrochloride amp', '50mg/ml', 4),
('Dopamine Hydrochloride amp', '40mg/ml (5ml)', 4),
('Dobutamine vial', '12.5mg/ml (250mg/20ml)', 4),
('Epinephrine ampule', '1mg/ml ', 4),
('Furosemide amp', '10mg/ml (2ml)', 4),
('Gentamicin Sulfate vial', '40mg/2ml', 4),
('Hydralazine Hydrochloride amp', '20mgml', 4),
('Hydrocortisone vial', '100mg', 4),
('Hyoscine N Butyl Bromide amp', '20mg/ml', 4),
('Ipratropium + Salbutamol amp', '200mcg/ml', 4),
('Isoxsuprine amp', '5mg/ml', 4),
('Ketorolac trometamol amp', '30mg/ml', 4),
('Levofloxacin vial', '5mg/mml (100ml)', 4),
('Lidocaine polyamp', '20% 5ml', 4),
('Magnesium Sulfate vial', '250mg/ml (20ml)', 4),
('Meropenem vial', '1g', 4),
('Meropenem vial', '500mg', 4),
('Metronidazole vial', '5mg/ml (100ml)', 4),
('Nicardipine Hydrochloride amp', '1mg/ml (10ml)', 4),
('Norepinephrine amp', '1mg/ml (4ml)', 4),
('Omeprazole vial', '40mg', 4),
('Ondansetron Hydrochloride Dihydrate ampule', '2mg/ml (4ml) ', 4),
('Paracetamol vial', '10mg/ml (100ml)', 4),
('Paracetamol amp', '150mg/ml (2ml)', 4),
('Phytomenadione amp', '10mg/ml', 4),
('Piperacillin + Tazobactam vial', '4.5g', 4),
('Potassium Chloride amp', '20mEq', 4),
('Propofol vial', '10mg/ml (20ml)', 4),
('Phenytoin amp', '50mg/ml', 4),
('Ranitidine amp', '25mg/ml', 4),
('Sodium Bicarbonate amp', '84%/ml', 4),
('Sodium Chloride vial', '0.9% (50ml)', 4),
('Tramadol amp', '50mg/ml (2ml)', 4),
('Vancomycin vial', '1g', 4),
('Vancomycin vial', '500mg', 4),
('Vitamin B1 + B6 + B12 amp', '100mg/100mg/1mg (3ml)', 4),







